[10.0] Update README and refactor
savoirfairelinux/partner-addons pull request #39
Opened 2018-01-09 19:25 UTC by yasmineelmrini

2018-01-10 14:24 UTC, ghost requested changes

2018-01-10 14:24 UTC, dufresnedavid commented on partner_duplicate_mgmt/README.rst
> +Possible
Please make complete sentences. You should only have one section explaining that merger between a company and a contact is not possible.

2018-01-10 14:24 UTC, dufresnedavid commented on partner_duplicate_mgmt/README.rst
> +"Contacts Merge With Account Moves", if not the merger won't be possible.
The name of the section should be something like:

Merging Partners with Account Moves
----------------------------------------------
...


The reason is that this feature is unrelated to the partner being a contact or a company. Also, the name of the group is incorrect. It should be "Partner Merge With Account Moves". If the 2 partners have account moves, the user must be part of the group in order to merge these partners.

2018-01-29 19:47 UTC, ddufresne approved these changes

2018-01-29 19:48 UTC, ghost approved these changes

2018-01-29 19:48 UTC, merged