[10.0] Add google_city_validation
savoirfairelinux/partner-addons pull request #51
Opened 2018-03-29 22:01 UTC by yasmineelmrini

2018-05-17 14:22 UTC, joaoalf requested changes

2018-05-17 14:22 UTC, joaoalf commented on google_city_validation/data/ir_config_parameter.xml
> +  <data>
@rimbendhaou It's better to use `noupdate` here.

2018-05-17 14:22 UTC, joaoalf commented on google_city_validation/models/res_config.py
> +        ).get_param('google_city_validation.policy')
@rimbendhaou indentation?

2018-05-17 14:22 UTC, joaoalf commented on google_city_validation/static/src/js/google_city_validation.js
> +                console.log('policy')
@rimbendhaou ??

2018-05-17 14:22 UTC, joaoalf commented on google_city_validation/static/src/js/google_city_validation.js
> +                console.log(policy)
@rimbendhaou ??

2018-05-17 14:22 UTC, joaoalf commented on google_city_validation/static/src/js/google_city_validation.js
> +                                 console.log('strict')
@rimbendhaou ??

2018-05-17 14:22 UTC, joaoalf commented on google_city_validation/static/src/js/google_city_validation.js
> +                                 alert("This city doesn't exist.");
@rimbendhaou I'm not sure that `alert()` is the proper odoo way to return a msg to the user.

2018-05-17 14:22 UTC, joaoalf commented on google_city_validation/static/src/js/google_city_validation.js
> +                                 console.log('soft')
@rimbendhaou ??

2018-05-22 13:46 UTC, joaoalf commented
@rimbendhaou Can you just clean-up a bit the git history? We should not see the merge commit and you add an internal ticket number in the commit prefix.

2018-05-22 15:23 UTC, rimbendhaou commented
@joaoalf ok

2018-05-22 21:28 UTC, joaoalf approved these changes

2018-05-23 21:19 UTC, merged