[Add] Add Full address field to copy autocompleted place field
savoirfairelinux/partner-addons pull request #54
Opened 2018-07-24 22:43 UTC by rimbendhaou

Add Full address field to copy autocompleted place field

2018-07-24 23:02 UTC, Ehtaga requested changes

2018-07-24 23:02 UTC, Ehtaga commented on google_partner_address/i18n/fr.po
> +msgstr "Localisation (Google map)"
Pourquoi avoir traduit comme ça? (maps prend un s)

2018-07-24 23:02 UTC, Ehtaga commented on google_partner_address/i18n/fr.po
> +#~ msgstr "Google Maps Api"
à supprimer

2018-07-24 23:02 UTC, Ehtaga commented on google_partner_address/i18n/fr.po
> +msgstr ""
Il manque les traductions

2018-07-25 17:26 UTC, rimbendhaou commented on google_partner_address/i18n/fr.po
> +msgstr "Localisation (Google map)"
@Ehtaga ok

2018-07-25 17:26 UTC, rimbendhaou commented on google_partner_address/i18n/fr.po
> +#~ msgstr "Google Maps Api"
@Ehtaga ok

2018-07-25 17:26 UTC, rimbendhaou commented on google_partner_address/i18n/fr.po
> +msgstr ""
@Ehtaga ok

2019-05-15 16:40 UTC, closed without merging